name: Build raspberry ONLINE

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
   
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Running Scripts
      run: |
        ls -a
        cd /opt/veye_raspberrypi
        rm /etc/apt/sources.list
        touch /etc/apt/sources.list
        echo "deb http://mirror.netcologne.de/raspbian/raspbian/ bullseye main contrib non-free" > /etc/apt/sources.list
        apt update
        ls -a
        mkdir /data/
        cp -r .git /data/.git/
        cp -r i2c_cmd /data/i2c_cmd/
        cp -r veye_raspcam /data/veye_raspcam/
        cp -r package.sh /data/
        cd /data/
        echo "starting build"
        sudo ./package.sh armhf raspbian bullseye
        ls -a

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "veye_raspberrypi"
        path: |
          *.deb
          
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-evo"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "veye_raspberrypi/*.deb"
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
