name: Build raspberry ONLINE

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
   
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Emulating Raspberry Pi 4
      id: qemu
      uses: pguyot/arm-runner-action@1be4bc9de8a7ba3c1c4f5bf917c438e8dc97904b
      with:
        base_image: http://openhdfpv.org/wp-content/BaseImages/OpenHD-image-pi-bullseye-milestone--2.1-milestones-2022-05-28_1033.zip
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: veye_raspberrypi
        import_github_env: true
        cpu: cortex-a53
        commands: |
            ls -a
            cd /opt/veye_raspberrypi
            rm /etc/apt/sources.list
            touch /etc/apt/sources.list
            echo "deb http://mirror.netcologne.de/raspbian/raspbian/ bullseye main contrib non-free" > /etc/apt/sources.list
            apt update
            sudo bash install_dep.sh
            ls -a
            mkdir /data/
            cp -r .git /data/.git/
            cp -r i2c_cmd /data/i2c_cmd/
            package.sh /data/
            cd data
            sudo ./package.sh armhf raspbian bullseye
            ls -a

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "veye_raspberrypi"
        path: |
          *.deb
          
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-evo"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "veye_raspberrypi/*.deb"
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
